module.exports = {
            nomeArquivo: 'relatorio.xls',
            hotel_nome: 'Hotel Rio Mar',
            hotel_cnpj: '99.999.999/9999-99',
            checkIn: '',
            checkOut: '',
            nome: '',
            uh : '',
            data_nascimento: '',
            nacionalidade: '',
            tipoDocto: '',
            numeroDocto: '',
            profissao: '',
            rua: '',
            numero: '',
            bairro: '',
            cidade: '',
            codigoCidade : '',
            estado: '',
            cep: '',
            email: '',
            naodefinido : 'nao definido'
        };